apiVersion: v1
kind: Pod
metadata:
  name: log-writer
  namespace: default
spec:
  containers:
    - name: logs-pv-container
      image: busybox
      command:
        - "sh"
        - "-c"
        - "while true; do echo $(date) >> /var/log/app/app.log; sleep 10; done"
      volumes:
    - name: logs-pv
      persistentVolumeClaim:
        claimName: log-pv-claim
  volumeMounts:
        - mountPath: "/var/log/app"
          name: logs-pv

