apiVersion: v1
kind: Pod
metadata:
  name: jaba
  labels:
        app: jaba
spec:
  containers:
  - name: ria
    image: sha256:5b14500a9778ddde820f03237cb37e7631c295d1c62c83fe5b5c334684ddea5b
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jaba
  namespace: default
  labels:
    app: jaba
 
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: jaba
  type: LoadBalancer
