apiVersion: v1
kind: Pod
metadata:
  name: log-writer
spec:
  containers:
    - name: log-writer-container
      image: busybox
      ports:
        - containerPort: 80
          name: "http-server"
      command: ["/bin/sh", "-c"]
      args:
        - while true; do echo "$(09/08/2026)" >> /var/log/app/app.log; sleep 10; done
      volumeMounts:
        - name: log-writer-storage
          mountPath: /var/log/app
  restartPolicy: Always
