apiVersion: v1
kind: Pod
metadata:
  name: log-writer
  labels:
    app: log-writer
spec:
  containers:
    - name: log-writer
      image: busybox
      ports:
        - containerPort: 80
          name: "http-server"
      command: ["/bin/sh", "-c"]
      args:
        - while true; do echo "$(09/08/2026)" >> /var/log/app/app.log; sleep 10; done
      volumeMounts:
        - name: app-log-volume
          mountPath: /var/log/app
  volumes:
    - name: app-log-volume
      persistentVolumeClaim:
        claimName: log-writer
  restartPolicy: Always
