apiVersion: v1
kind: Pod
metadata:
  name: log-writer
  namespace: default
spec:
  containers:
    - name: log-writer
      image: busybox
      command:
        - "sh"
        - "-c"
        - "while true; do echo $(date) >> /var/log/app/app.log; sleep 10; done"
      volumeMounts:
        - name: logs-volume
          mountPath: /var/log/app
  volumes:
    - name: logs-volume
      persistentVolumeClaim:
        claimName: logs-pvc
