apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: blue-green-demo
spec:
  type: ClusterIP
  selector:
    app: nginx
    version: blue   # Initially pointing to BLUE version
  ports:
  - port: 80
    targetPort: 80
